<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.*" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.*" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.*" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.*" />
    <PackageReference Include="LibVLCSharp" Version="3.9.*" />
    <PackageReference Include="VideoLAN.LibVLC.Mac" Version="3.*" Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.*" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Asset/bell.png" />
    <Content Include="Asset/daojishi.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Asset/fzn15.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
